//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LeventsDBEntities : DbContext
    {
        public LeventsDBEntities()
            : base("name=LeventsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annons> Annons { get; set; }
        public virtual DbSet<Anvandare> Anvandare { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual int DeleteAnnons(Nullable<int> annonsID)
        {
            var annonsIDParameter = annonsID.HasValue ?
                new ObjectParameter("annonsID", annonsID) :
                new ObjectParameter("annonsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAnnons", annonsIDParameter);
        }
    }
}
